target-version = "py312"
line-length = 100

[lint]
select = [
  # Core style / errors
  "E","F","W",
  "I",               # import sorting (isort)
  "C",               # complexity (via mccabe)

  # HA-relevant best practices
  "ASYNC","LOG","G",
  "UP","PERF","PIE",
  "RET","RSE","BLE",
  "PTH","ICN","ISC",
  "PT",              # pytest style
  "B",               # bugbear

  # Footgun catchers
  "RUF006",          # save create_task return value
  "RUF100",          # dead noqa
  "PGH004",          # # noqa must include codes
  "PLC0414",         # useless import alias
  "T20",             # no print()

  # Safe SIM refactors
  "SIM105","SIM118","SIM201","SIM401",
  "SIM117", "SIM212", "SIM300",

  "TRY004"

]

# Formatter conflicts and pragmatic ignores
ignore = [
  "E501",            # line length (formatter handles it)
  "COM812","COM819", # comma/whitespace (formatter)
  "ISC001",          # implicit string concat (formatter)
  "W191","E111","E114","E117",  # edge indentation noise
  "D206","D300"      # docstring formatting quirks
]

[lint.isort]
force-sort-within-sections = true
known-first-party = ["custom_components.smappee_ev"]
combine-as-imports = true
split-on-trailing-comma = false

[lint.mccabe]
max-complexity = 18

[format]
docstring-code-format = true

[lint.per-file-ignores]
"custom_components/**/__init__.py" = ["F401"]  # re-export ok
"tests/**" = ["D","S101"]                      # 
