set_charging_mode:
  description: "Set the charging mode (NORMAL, SMART, SOLAR)."
  fields:
    config_entry_id:
      description: "Optional: Specific config entry id to target (when multiple entries)."
      required: false
      example: "a1b2c3d4e5f6"
    service_location_id:
      description: "Optional: Service Location ID."
      required: false
      example: 173311
      selector:
        number:
          min: 1
    connector_id:
      description: "Optional: Connector number."
      required: false
      example: 1
      selector:
        number:
          min: 1
    mode:
      description: "Charging mode to apply."
      required: true
      selector:
        select:
          options:
            - NORMAL
            - SMART
            - SOLAR

pause_charging:
  description: "Pause charging on a connector."
  fields:
    config_entry_id:
      description: "Optional: Specific config entry id to target (when multiple entries)."
      required: false
      example: "a1b2c3d4e5f6"
    service_location_id:
      description: "Optional: Service Location ID."
      required: false
      example: 173311
      selector:
        number:
          min: 1
    connector_id:
      description: "Optional: Connector number."
      required: false
      example: 1
      selector:
        number:
          min: 1

stop_charging:
  description: "Stop charging on a connector."
  fields:
    config_entry_id:
      description: "Optional: Specific config entry id to target (when multiple entries)."
      required: false
      example: "a1b2c3d4e5f6"
    service_location_id:
      description: "Optional: Service Location ID."
      required: false
      example: 173311
      selector:
        number:
          min: 1
    connector_id:
      description: "Optional: Connector number."
      required: false
      example: 1
      selector:
        number:
          min: 1

start_charging:
  description: "Start charging on a connector. "
  fields:
    config_entry_id:
      description: "Optional: Specific config entry id to target (when multiple entries)."
      required: false
      example: "a1b2c3d4e5f6"
    service_location_id:
      description: "Optional: Service Location ID."
      required: false
      example: 173311
      selector:
        number:
          min: 1
    connector_id:
      description: "Optional: Connector number."
      required: false
      example: 1
      selector:
        number:
          min: 1
    current:
      description: "Optional: Charging current in Ampere"
      required: false
      example: 16
      selector:
        number:
          min: 6
          max: 32
          unit_of_measurement: "A"
