set_charging_mode:
  description: "Set the charging mode (NORMAL, SMART, SOLAR)."
  fields:
    connector_id:
      description: "Connector number (1 or 2)."
      required: false
      selector:
        number:
          min: 1
          max: 2
    mode:
      description: "Charging mode to apply."
      required: true
      selector:
        select:
          options:
            - "NORMAL"
            - "SMART"
            - "SOLAR"
    limit:
      description: "Optional current limit in Ampere when mode is NORMAL."
      required: false
      selector:
        number:
          min: 6
          max: 32
          unit_of_measurement: "A"

pause_charging:
  description: "Pause charging on a connector."
  fields:
    connector_id:
      description: "Connector number (1 or 2)."
      required: false
      selector:
        number:
          min: 1
          max: 2

stop_charging:
  description: "Stop charging on a connector."
  fields:
    connector_id:
      description: "Connector number (1 or 2)."
      required: false
      selector:
        number:
          min: 1
          max: 2
  

start_charging:
  description: "Start charging on a connector using a specific current value (Ampere)."
  fields:
    connector_id:
      description: "Connector number (1 or 2). If omitted, the only available connector is used."
      example: 1
      required: false
      selector:
        number:
          min: 1
          max: 2
    current:
      description: "Charging current in Ampere"
      example: 16
      required: true
      selector:
        number:
          min: 6
          max: 32
          unit_of_measurement: "A"

set_brightness:
  description: "Set the LED brightness of the station."
  fields:
    brightness:
      description: "LED brightness percentage (e.g., 3, 70)"
      example: 70
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_available:
  description: "Set the charging station as available."
  fields: {}

set_unavailable:
  description: "Set the charging station as unavailable."
  fields: {}

reload:
  name: Reload integration
  description: Reload all Smappee EV entries and refresh the integration.
  fields: {}
