set_charging_mode:
  description: "Set the charging mode of a connector."
  fields:
    serial:
      description: "Serial number of the charging station"
      example: "6220001089"
    mode:
      description: "Charging mode to set (NORMAL, NORMAL_PERCENTAGE, SMART, SOLAR)"
      example: "NORMAL"
    limit:
      description: "Current limit in amperes"
      example: 6

pause_charging:
  name: Pause Charging
  description: "Pauses charging via the Smappee API."

stop_charging:
  name: Stop Charging
  description: "Stops charging via the Smappee API."
  
start_charging:
  description: "Start charging with optional percentage limit"
  fields:
    percentageLimit:
      description: "Percentage limit for charging"
      example: 5

set_brightness:
  description: Set the LED brightness of the charger.
  fields:
    brightness:
      description: Brightness level (0-100)
      example: 15

set_available:
  description: Set the smart charger to available state.

set_unavailable:
  description: Set the smart charger to unavailable state.

reload:
  name: Reload integration
  description: Reload all Smappee EV entries and refresh the integration.
