blueprint:
  name: "Smappee: Sun-based LED brightness"
  description: Adjust LED brightness at sunrise and sunset with configurable offsets.
  domain: automation
  input:
    target_light:
      name: Light
      selector:
        entity:
          domain: light
          integration: smappee_ev
    sunrise_offset:
      name: Sunrise offset
      default: "00:00:00"
      selector:
        time:
    sunset_offset:
      name: Sunset offset
      default: "00:00:00"
      selector:
        time:
    sunrise_brightness:
      name: Sunrise brightness
      default: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    sunset_brightness:
      name: Sunset brightness
      default: 2
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

mode: single
triggers:
  - trigger: sun
    event: sunrise
    offset: !input sunrise_offset
    id: sunrise
  - trigger: sun
    event: sunset
    offset: !input sunset_offset
    id: sunset
actions:
  - if:
      - condition: trigger
        id: sunrise
    then:
      - action: light.turn_on
        target:
          entity_id: !input target_light
        data:
          brightness_pct: !input sunrise_brightness
    else:
      - action: light.turn_on
        target:
          entity_id: !input target_light
        data:
          brightness_pct: !input sunset_brightness
